//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFILIADOSAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AFILIADOS_IGNACIOEntities : DbContext
    {
        public AFILIADOS_IGNACIOEntities()
            : base("name=AFILIADOS_IGNACIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AFILIADOS> AFILIADOS { get; set; }
        public virtual DbSet<ESTATUS> ESTATUS { get; set; }
        public virtual DbSet<PLANES> PLANES { get; set; }
    }
}
