//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFILIADOSAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class AFILIADOS
    {
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        public string Sexo { get; set; }
        [Required]
        public string Cedula { get; set; }
        [Required]
        public string NSS { get; set; }
        [DataType(DataType.Date)]
        [Required]
        [Display(Name ="Registro")]
        public System.DateTime FechaRegistro { get; set; }
        [Display(Name = "Monto Consumido")]
        [Required]
        public double MontoConsumido { get; set; }
        [Required]
        public int EstatusId { get; set; }
        [Display(Name = "Plan")]
        [Required]
        public int PlanId { get; set; }
    
        public virtual ESTATUS ESTATUS { get; set; }
        public virtual PLANES PLANES { get; set; }

        [NotMapped]
        public SelectList EstatusList { get; set; }
        [NotMapped]
        public SelectList PlanesList { get; set; }
    }
}
