//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFILIADOSAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class PLANES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANES()
        {
            this.AFILIADOS = new HashSet<AFILIADOS>();
        }
    
        public int Id { get; set; }
        [Required]
        [Display(Name ="Plan")]
        public string PlanDescripcion { get; set; }
        [Required]
        [Display(Name = "Cobertura")]
        public double MontoCobertura { get; set; }
        [DataType(DataType.Date)]
        [Required]
        [Display(Name = "Registro")]
        public System.DateTime FechaRegistro { get; set; }
        [Required]
        public int EstatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AFILIADOS> AFILIADOS { get; set; }
        public virtual ESTATUS ESTATUS { get; set; }

        [NotMapped]
        public SelectList EstatusList { get; set; }
    }
}
